name: Dispatch

on:
  push:
    branches:
      - dev
    paths:
      - '**.java'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/shipping.yaml'  # Include workflow file changes 

  pull_request:
    branches:
      - master
    paths:
      - '**.java'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/shipping.yaml'  # Include workflow file changes

jobs:
  payment:
    name: Build and deploy shipping microservice
    runs-on: ubuntu-latest

    env:
      ACR_NAME: acr98794tf47                     # ðŸ”¹ Replace with your ACR name (without .azurecr.io)
      IMAGE_NAME: shipping                         # ðŸ”¹ Your microservice name
      # AKS_RESOURCE_GROUP: rg-aks-dev           # ðŸ”¹ Your AKS resource group
      # AKS_CLUSTER_NAME: aks-dev-cluster        # ðŸ”¹ Your AKS cluster name
      # NAMESPACE: default                       # ðŸ”¹ Kubernetes namespace

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  Java Install
        run: |
            sudo apt-get install openjdk 17 |
            java -version 

      - name: Build Docker image
        working-directory: shipping
        run: |
          docker build -t $ACR_NAME.azurecr.io/robotshop/$IMAGE_NAME:latest .
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          # ðŸ‘‡ Example secret value (JSON format):
          # {"clientId":"<id>","clientSecret":"<secret>","subscriptionId":"<sub>","tenantId":"<tenant>"}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/robotshop/$IMAGE_NAME:latest
      # - name: Get AKS credentials
      #   run: |
      #     az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
